import { UserProfile, LineageEdge, Post, InAppNotification, NotificationPreferences, AuditLog } from '@/types';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'user-001',
    family_id: 'OBEFF-00101',
    email: 'elder.obeff@family.org',
    first_name: 'Eteidung',
    last_name: 'Obeff',
    phone: '+234 803 111 2222',
    address: '14 Heritage Boulevard, Calabar, Nigeria',
    date_of_birth: '1948-04-12',
    role: 'Super-Admin',
    status: 'Active',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'user-002',
    family_id: 'OBEFF-00102',
    email: 'maria.obeff@family.org',
    first_name: 'Maria',
    last_name: 'Obeff',
    phone: '+234 802 333 4444',
    address: '14 Heritage Boulevard, Calabar, Nigeria',
    date_of_birth: '1952-09-25',
    role: 'Member',
    status: 'Active',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-02T11:00:00Z',
  },
  {
    id: 'user-003',
    family_id: 'OBEFF-00103',
    email: 'dr.edet@family.org',
    first_name: 'Dr. Edet',
    last_name: 'Obeff',
    phone: '+234 805 555 6666',
    address: '8 Marina Road, Lagos, Nigeria',
    date_of_birth: '1975-06-18',
    role: 'Admin',
    status: 'Active',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-05T09:30:00Z',
  },
  {
    id: 'user-004',
    family_id: 'OBEFF-00104',
    email: 'kufre.obeff@family.org',
    first_name: 'Kufre',
    last_name: 'Obeff',
    phone: '+44 7700 900123',
    address: '22 Kensington High St, London, UK',
    date_of_birth: '1998-11-04',
    role: 'Member',
    status: 'Active',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-01-10T14:15:00Z',
  },
  {
    id: 'user-005',
    family_id: 'OBEFF-00105',
    email: 'anima.obeff@family.org',
    first_name: 'Anima',
    last_name: 'Obeff',
    phone: '+234 818 777 8888',
    address: '5 Independence Way, Abuja, Nigeria',
    date_of_birth: '2003-02-14',
    role: 'Member',
    status: 'Pending',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-09-18T16:00:00Z',
  },
];

export const INITIAL_LINEAGE: LineageEdge[] = [
  {
    id: 'edge-001',
    child_id: 'user-003',
    parent_id: 'user-001',
    relation_type: 'Father',
    approval_status: 'Approved',
    approved_by: 'user-001',
    approved_at: '2026-01-05T10:00:00Z',
    created_at: '2026-01-05T09:40:00Z',
  },
  {
    id: 'edge-002',
    child_id: 'user-003',
    parent_id: 'user-002',
    relation_type: 'Mother',
    approval_status: 'Approved',
    approved_by: 'user-001',
    approved_at: '2026-01-05T10:00:00Z',
    created_at: '2026-01-05T09:40:00Z',
  },
  {
    id: 'edge-003',
    child_id: 'user-004',
    parent_id: 'user-003',
    relation_type: 'Father',
    approval_status: 'Approved',
    approved_by: 'user-001',
    approved_at: '2026-01-10T15:00:00Z',
    created_at: '2026-01-10T14:20:00Z',
  },
  {
    id: 'edge-004',
    child_id: 'user-005',
    parent_id: 'user-003',
    relation_type: 'Father',
    approval_status: 'Pending',
    created_at: '2026-09-18T16:10:00Z',
    notes: 'Submitted for verification under Dr. Edet branch.',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-001',
    author_id: 'user-001',
    author: INITIAL_PROFILES[0],
    content: '🕊️ Official Family Announcement: The Annual OBEFF General Assembly and Thanksgiving will take place on December 28th, 2026. All diaspora branches are encouraged to submit their delegate lists by November 15th. Full schedule attached below.',
    media_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    is_admin_announcement: true,
    is_pinned: true,
    likes_count: 24,
    comments_count: 5,
    has_liked: true,
    created_at: '2026-09-15T08:00:00Z',
    comments: [
      {
        id: 'c-1',
        post_id: 'post-001',
        author_id: 'user-003',
        author: INITIAL_PROFILES[2],
        content: 'Noted with thanks, Father. The Lagos branch is coordinating travel plans.',
        created_at: '2026-09-15T09:30:00Z',
      },
      {
        id: 'c-2',
        post_id: 'post-001',
        author_id: 'user-004',
        author: INITIAL_PROFILES[3],
        content: 'Looking forward to seeing everyone in December! UK flight booked.',
        created_at: '2026-09-15T11:45:00Z',
      }
    ]
  },
  {
    id: 'post-002',
    author_id: 'user-004',
    author: INITIAL_PROFILES[3],
    content: 'Just received my Masters in Artificial Intelligence from Imperial College London! Immensely grateful for all the prayers and support from the entire OBEFF family. Here is a short highlight reel from graduation day! 🎓🎉',
    media_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80',
    is_admin_announcement: false,
    is_pinned: false,
    likes_count: 38,
    comments_count: 8,
    has_liked: false,
    created_at: '2026-09-18T14:20:00Z',
    comments: [
      {
        id: 'c-3',
        post_id: 'post-002',
        author_id: 'user-001',
        author: INITIAL_PROFILES[0],
        content: 'Hearty congratulations, my grandson! You make the entire lineage proud.',
        created_at: '2026-09-18T15:00:00Z',
      }
    ]
  },
];

export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-001',
    recipient_id: 'user-001',
    type: 'Approval',
    title: 'New Member Registration',
    message: 'Anima Obeff registered and is awaiting admin approval.',
    action_url: '/admin/approvals',
    is_read: false,
    created_at: '2026-09-18T16:00:00Z',
  },
  {
    id: 'notif-002',
    recipient_id: 'user-001',
    type: 'Approval',
    title: 'Lineage Verification Request',
    message: 'Anima Obeff submitted parental link to Dr. Edet Obeff.',
    action_url: '/admin/approvals',
    is_read: false,
    created_at: '2026-09-18T16:10:00Z',
  },
  {
    id: 'notif-003',
    recipient_id: 'user-004',
    type: 'Announcement',
    title: 'New Official Announcement',
    message: 'Eteidung Obeff pinned: Annual OBEFF General Assembly & Thanksgiving.',
    action_url: '/feed',
    is_read: true,
    created_at: '2026-09-15T08:00:00Z',
  },
  {
    id: 'notif-004',
    recipient_id: 'user-004',
    type: 'Engagement',
    title: 'New Comment on Your Post',
    message: 'Eteidung Obeff commented on your graduation update.',
    action_url: '/feed',
    is_read: false,
    created_at: '2026-09-18T15:00:00Z',
  },
];

export const INITIAL_PREFERENCES: Record<string, NotificationPreferences> = {
  'user-001': {
    profile_id: 'user-001',
    email_announcements: true,
    email_new_posts: false,
    email_engagements: true,
  },
  'user-003': {
    profile_id: 'user-003',
    email_announcements: true,
    email_new_posts: true,
    email_engagements: true,
  },
  'user-004': {
    profile_id: 'user-004',
    email_announcements: true,
    email_new_posts: false,
    email_engagements: true,
  },
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    admin_id: 'user-001',
    admin_name: 'Eteidung Obeff',
    target_user_id: 'user-003',
    target_user_name: 'Dr. Edet Obeff',
    action_type: 'ROLE_PROMOTED_TO_ADMIN',
    metadata: { role: 'Admin', reason: 'Designated Lagos Branch Coordinator' },
    created_at: '2026-01-05T10:05:00Z',
  },
  {
    id: 'log-002',
    admin_id: 'user-001',
    admin_name: 'Eteidung Obeff',
    target_user_id: 'user-004',
    target_user_name: 'Kufre Obeff',
    action_type: 'ACCOUNT_ACTIVATED',
    metadata: { family_id: 'OBEFF-00104' },
    created_at: '2026-01-10T15:00:00Z',
  },
  {
    id: 'log-003',
    admin_id: 'user-001',
    admin_name: 'Eteidung Obeff',
    target_user_id: 'user-004',
    target_user_name: 'Kufre Obeff',
    action_type: 'LINEAGE_APPROVED',
    metadata: { relation: 'Father', parent: 'Dr. Edet Obeff' },
    created_at: '2026-01-10T15:02:00Z',
  },
];
